### ISSUE TITLE
IP Forwarding is broken for newest docker version

### ISSUE THREAD

**Issue by martinlasek** [AlmirKadric-Published/docker-tuntap-osx#13]
**Docker Version:** 17.12.0-ce-mac46

The command
```
docker run --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i iptables -A FORWARD -i eth1 -j ACCEPT
```

would not work anymore and gives the following error:
```
nsenter: failed to execute iptables: No such file or directory
```

**Comment by ondraondra81** [comment]
@MartinLasek and you have not problem with install script? because I getting error message that docker can not restarting.

About your issue. I think that in docker host is UFW instead of iptables now

**Comment by martinlasek** [comment]
I had a problem with the install script until I pulled in the latest state of the master branch 😊

**Comment by AlmirKadric** [comment]
I'll take a look today and get the README updated with the correct command
thanks for the report!

**Comment by ondraondra81** [comment]
@AlmirKadric @MartinLasek think that IP Forwarding working out of box now. I didn't need run any command for FW unlocked and all working ok. 
I  have:
Client:
 Version:	17.12.0-ce
 API version:	1.35
 Go version:	go1.9.2
 Git commit:	c97c6d6
 Built:	Wed Dec 27 20:03:51 2017
 OS/Arch:	darwin/amd64

Server:
 Engine:
  Version:	17.12.0-ce
  API version:	1.35 (minimum version 1.12)
  Go version:	go1.9.2
  Git commit:	c97c6d6
  Built:	Wed Dec 27 20:12:29 2017
  OS/Arch:	linux/amd64
  Experimental:	true

and macOS High Sierra version 10.13.2

**Comment by AlmirKadric** [comment]
@ondraondra81 @MartinLasek Sorry for the delay, I also upgraded and tried it on my mac and it seems the remove the firewall all together (pure linuxkit I guess). So the firewall settings inside the Host VM are no longer needed for the tap interface. I'll update the readme 👍

**Comment by AlmirKadric** [comment]
updated readme, let me know if this is ok, if so I'll merge and close this issue 👍

**Comment by AlmirKadric** [comment]
got no response so will move ahead with the changes
tested to work on several projects
feel free to re-open if the issues still persists for you
