### ISSUE TITLE
Conflicts with my VPN

### ISSUE THREAD

**Issue by charandas** [AlmirKadric-Published/docker-tuntap-osx#16]
After doing a `docker_tap_up.sh`, I cannot do docker builds that require my npm registry accessible over vpn in 10.x range.

Is there something simple I can do regarding it?

```
# inside a test busybox container
/ # netstat -nr
Kernel IP routing table
Destination     Gateway         Genmask         Flags   MSS Window  irtt Iface
0.0.0.0         192.168.65.1    0.0.0.0         UG        0 0          0 eth0
10.0.0.0        0.0.0.0         255.0.0.0       U         0 0          0 eth1
127.0.0.0       0.0.0.0         255.0.0.0       U         0 0          0 lo
172.17.0.0      0.0.0.0         255.255.0.0     U         0 0          0 docker0
172.18.0.0      0.0.0.0         255.255.0.0     U         0 0          0 br-293cf0386986
192.168.65.0    0.0.0.0         255.255.255.0   U         0 0          0 eth0
```

Clearly the `10.0.0.0` entry won't let it get to my npm which is at `10.21.x.y`.

**Comment by AlmirKadric** [comment]
Yest there is, its actually been on my todo list for a while here https://github.com/AlmirKadric-Published/docker-tuntap-osx/issues/3
You can send a PR and I would be happy to review and merge it
you can make the `10.x` range ip's configurable via ENV variables here
https://github.com/AlmirKadric-Published/docker-tuntap-osx/blob/master/sbin/docker_tap_up.sh#L10

something like this should suffice, but would need to be tested:
```
localGateway='10.0.75.1/24'
hostGateway='10.0.75.2'
test -n "${DTOSX_LOCAL_GATEWAY}" && localGateway="${DTOSX_LOCAL_GATEWAY}"
test -n "${DTOSX_HOST_GATEWAY}" && hostGateway="${DTOSX_HOST_GATEWAY}"
```

**Comment by charandas** [comment]
I considered your advice @AlmirKadric. However, using a 192 subnet led to other problems like not being able to connect to GitHub.

A simpler hack I came up with, was to copy script `./sbin/docker_tap_up.sh` to `./sbin/docker_tap_down.sh` (with the word `up` replaced by `down` on the ifconfig line). This restores my ability to build against my registry over VPN.

**Comment by AlmirKadric** [comment]
@charandas sure but that still makes the setup incompatible with your VPN and now you're required to switch between the 2. In my suggestion you're not limited to the `10.x` and `192.x` range, not sure why you assumed I recommended using the `192.x` range. You can take the range `11.x` for example and it will still work. The idea is that you need to use a subnet which doesn't conflict with other subnets you have configured in your routing table. Am I missing something here?

My suggestion is merely to allow users to configure the subnet so they can use what is appropriate to their current environment through the use of environment variables. e.g. run the script as such `DTOSX_LOCAL_GATEWAY="11.0.75.1/24" DTOSX_HOST_GATEWAY="11.0.75.2" ./sbin/docker_tap_up.sh` or putting `export DTOSX_LOCAL_GATEWAY="11.0.75.1/24"` inside their `.bash_profile` etc.

**Comment by charandas** [comment]
Thanks much again.

I only know of a 10, 172, 192 range recommended by IETF for internal use.

In my case, all of those ranges are in use in my company environment when I vpn in.

How can I ever be sure when using the 11.x example that I won’t run to other connectivity issues to other websites while simply browsing?

**Comment by AlmirKadric** [comment]
@charandas  That is true, you could run into issues if you are browsing and a site happens to fall under the `11.x` range. My final question then would be (though honestly outside the the scope of this project and more an issue with how you're doing networking) why is your local network / VPN using the entire `10.x` and `192.x` range? Or is there a subnet in the `172.x` range you can use? Generally when a VPN is setup, they would carve out a similar subnet as to what is already assigned within the remote network. Are those networks (remote VPN and your local network) really using a `255.0.0.0` mask? Can you not configure this to be something more like `255.255.255.0` or `255.255.0.0`?

Lastly you could play around with your routing table to pick an IP within one of the taken ranges to fall out of the routing all other IPs in that range follow. e.g. hijacking `10.0.75.1` and `10.0.75.2` (or any IP for that matter) to go to `tap1` interface and all other ips in the `10.x` range going to your VPN gateway.

Apart from this (and perhaps delving in IPv6) honestly I don't know what else you could do, this is very much an issue with the way your network is setup.

**Comment by AlmirKadric** [comment]
@charandas did you managed to resolve your issue? is there any other follow up you would like to do? or can I close this issue?

**Comment by charandas** [comment]
You can close this issue @AlmirKadric. Thanks for your attention to detail.

For now, I am using the scripts as they are, knowing the limitations of my network. Perhaps, someday I will play with the routing table as suggested, but for now, I am satisfied.
