### ISSUE TITLE
"The hyperkit executable file was of an unknown type" when installer is run twice

### ISSUE THREAD

**Issue by pts-rajperera** [AlmirKadric-Published/docker-tuntap-osx#20]
This is most likely related to #4 

I ran in to this issue as well trying to run the install script twice. The error "The hyperkit executable file was of an unknown type" seems to be coming  from the installer script because it checks the file type of the of the hyperkit shim by using the `file` command. In my machine the output of the command is 
```
$ file /Applications/Docker.app/Contents/Resources/bin/hyperkit                                                                                                           
/Applications/Docker.app/Contents/Resources/bin/hyperkit: Bourne-Again shell script text executable
```
and the script checks for https://github.com/AlmirKadric-Published/docker-tuntap-osx/blob/master/sbin/docker_tap_install.sh#L66
```
if file "$hyperkitPath" | grep -q 'executable, ASCII text$'; then
```

**Comment by AlmirKadric** [comment]
ah right, that is indeed an issue, I'll try and get it fixed over the next few days
if you can't wait, mind making a PR? I'm more than happy to review it

**Comment by AlmirKadric** [comment]
this should be fixed in the latest commit
do you mind pulling and trying again?

**Comment by AlmirKadric** [comment]
will close due to inactivity, if anyone has this problem again please make another issue
