### ISSUE TITLE
Errors when restarting docker after installation

### ISSUE THREAD

**Issue by m0rff** [AlmirKadric-Published/docker-tuntap-osx#22]
```
> ./sbin/docker_tap_install.sh
Installation complete
Restarting process 'com.docker.hyperkit' [33651]

Failed to restart process 'com.docker.hyperkit'
```

Then I manually restarted Docker.

```
> ./sbin/docker_tap_up.sh
Unable to find image 'alpine:latest' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/: proxyconnect tcp: dial tcp: lookup docker.for.mac.http.internal on 192.168.65.1:53: read udp 192.168.65.1:39602->192.168.65.1:53: read: connection refused.
See 'docker run --help'.
```

**Comment by gmuloc** [comment]
Hi,

I did the install yesterday and encountered the same issues.
First one:
The install script did not copy ```./sbin/docker.hyperkit.tuntap.sh``` to replace the ```hyperkit``` binary though the binary was indeed copy to ```hyperkit.original```.

I just did the copy step manually
```cp ./sbin/docker.hyperkit.tuntap.sh /Applications/Docker.app/Contents/Resources/bin/hyperkit```

and then was able to restart docker.

I also got the issue for alpine:latest
what I did is I pulled it first
``` 
docker pull alpine:latest
```
and then I just ran the script again and it worked.

I am running Sierra 10.12.6 and Docker version 18.03.1-ce, build 9ee9f40

HTH

**Comment by m0rff** [comment]
I reseted Docker to factory settings and now it's working. I may have had set a wrong IP address in the Docker network preferences.

**Comment by AlmirKadric** [comment]
@gmuloc thanks for the help!
@m0rth1um can i consider this issue resolved?

**Comment by m0rff** [comment]
@AlmirKadric Yes

**Comment by AlmirKadric** [comment]
@m0rth1um thanks for the quick reply!
