### ISSUE TITLE
18.03.1-ce-mac65 - The system does not work anymore

### ISSUE THREAD

**Issue by ArsBinarii** [AlmirKadric-Published/docker-tuntap-osx#23]
Mac OS: 10.13.5 (17F77)

Docker
Version 18.03.1-ce-mac65
Engine: 18.03.1-ce
Compose: 1.21.1

./docker_tap_install.sh - crashes the docker and it never recovers, you need to quit an start again, reports installed after

./docker_tap_install.sh -f
Restarting process 'com.docker.hyperkit' [57982] results in Fatal Error - com.docker.supervisor failed to start - Exit code 1

./docker_tap_up.sh - runs but you can't connect to the machine

The system does not work anymore

**Comment by AlmirKadric** [comment]
thanks for reporting, will take a look 👍

**Comment by ArsBinarii** [comment]
Mac OS: 10.12.6 (16G1314)

Docker
Version 18.03.1-ce-mac65
Engine: 18.03.1-ce
Compose: 1.21.1

./docker_tap_install.sh - 
Installation complete
Restarting process 'com.docker.hyperkit' [61885]
Failed to restart process 'com.docker.hyperkit'

The Docker is just stuck in starting after 15 min I restarted the Docker.

./docker_tap_install.sh - 
Already installed
Use "-f" argument if you want to restart hyperkit anyway

./docker_tap_up.sh - runs but you can't connect to the machine

**Comment by AlmirKadric** [comment]
@RRPRIME sorry for the delay, i got sidetracked and forgot about this issue. I just tested this and apart from the restart step crashing docker (need to manually start up docker), it all seems to work fine on my end. Do you mind providing me with the following to help debug your situation:
 - `ls -l /Applications/Docker.app/Contents/Resources/bin/` to make sure the shim was properly installed and configured
 - `ls -l /dev/tap*` to make sure docker has access to tap interface
 - `ifconfig` to make sure docker connected to the tap interface
 - `netstat -rn` to make sure routes were set to the containers over the tap interface
 - `docker run --rm --privileged --pid=host --net=host alpine ifconfig` to make docker created the target interface
 - `docker run --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i iptables-save` to make sure the docker host allows routing
 - `docker inspect <<Container_id>>` to make sure your container is configure to use all of the above

**Comment by AlmirKadric** [comment]
@RRPRIME are you still facing issues
I would like to clean up this issue
if i dont get a response by next i will be closing the issue

**Comment by fijimunkii** [comment]
@AlmirKadric I had the same issues on install. Restarted docker and the engine is running. The `ifconfig` entry for `tap1` looks correct.
```
tap1: flags=8843<UP,BROADCAST,RUNNING,SIMPLEX,MULTICAST> mtu 1500
	ether aa:a3:71:9e:6a:57 
	inet 10.0.75.1 netmask 0xffffff00 broadcast 10.0.75.255
	media: autoselect
	status: active
	open (pid 3136)
```
When running your debug commands I get stuck with:
`nsenter: failed to execute iptables-save: No such file or directory`

**Comment by lscgzwd** [comment]
I also got this.
```
Installation complete
Restarting process 'com.docker.hyperkit' [81067]

Failed to restart process 'com.docker.hyperkit'
```
But, I just ignore this. Reopen docker for mac . then exec ```./sbin/docker_tap_up.sh``` , It works fine for me.

**Comment by AlmirKadric** [comment]
this may have been fixed with #29 
can someone please take a look and let me know if it is resolved
CC: @lscgzwd  @fijimunkii

**Comment by AlmirKadric** [comment]
@RRPRIME @lscgzwd @fijimunkii are you guys still having those issues on the latest version?
please pull the latest code and re-install the shim with `./sbin/docker_tap_install.sh -f`
let me know if the problem still exists

**Comment by AlmirKadric** [comment]
will close due to inactivity, if anyone has this problem again please make another issue
