### ISSUE TITLE
Can't install plugin on macOS High Sierra 10.13.5

### ISSUE THREAD

**Issue by tonifirnandes** [AlmirKadric-Published/docker-tuntap-osx#24]
Dear team,

Please help us, when we did "brew cask install tuntap", we got error : 

brew cask install tuntap     
==> Caveats
To install and/or use tuntap you may need to enable their kernel extension in

  System Preferences → Security & Privacy → General

For more information refer to vendor documentation or the Apple Technical Note:

  https://developer.apple.com/library/content/technotes/tn2459/_index.html

==> Satisfying dependencies
==> Downloading https://downloads.sourceforge.net/tuntaposx/tuntap/20150118/tuntap_20150118.tar.gz
Already downloaded: /Users/tonifirnandes/Library/Caches/Homebrew/Cask/tuntap--20150118.tar.gz
==> Verifying checksum for Cask tuntap
==> Installing Cask tuntap
==> Running installer for tuntap; your password may be necessary.
==> Package installers may write to any location; options such as --appdir are ignored.
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)
==> Purging files for version 20150118 of Cask tuntap
Error: Command failed to execute!

==> Failed command:
/usr/bin/sudo -E -- env LOGNAME=tonifirnandes USER=tonifirnandes USERNAME=tonifirnandes /usr/sbin/installer -pkg /usr/local/Caskroom/tuntap/20150118/tuntap_20150118.pkg -target /

==> Standard Output of failed command:
installer: Package name is TunTap Installer package
installer: Installing at base path /
installer: The install failed (The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.)

==> Standard Error of failed command:

==> Exit status of failed command:
#<Process::Status: pid 5941 exit 1>

Thanks.

**Comment by AlmirKadric** [comment]
Hi @tonifirnandes ,
If you follow the exact instructions there it should work (I did the same thing a few days ago on my new macbook pro). After you attempt the installation, it will fail with the above message. If you then go to your `Systems Preferences` -> `Security & Privacy` (1st Tab - `General`) you will see an additional button near the `Allow apps downloaded from:` (see attached image)
![image](https://user-images.githubusercontent.com/1650294/42733555-fdb1aa8e-886d-11e8-9261-82aeb975e7b5.png)

Clicking this button will approve the installation, from there you can go and run the installation for tuntap again and it should install without issues.

Please let me know if this solves your problem, or if you run into any other issues.

**Comment by rhickstedjr** [comment]
I have the kext loaded (net.sf.tuntaposx.tap) but can't create the tap interface (trying to use for simh to get my VAX network operational):

Note:  installed via brew:

brew cask install tuntap

192-168-2-122:BIN rickhicksted2$ uname -a
Darwin Ricks-MBP-2 17.7.0 Darwin Kernel Version 17.7.0: Fri Jul  6 19:54:51 PDT 2018; root:xnu-4570.71.3~2/RELEASE_X86_64 x86_64

192-168-2-122:BIN rickhicksted2$ kextstat |grep -e tun -e tap
  170    0 0xffffff7f80ea4000 0x7000     0x7000     net.sf.tuntaposx.tun (1.0) 95DD963D-E23D-3B0F-8DE8-A4D2F6BFA5CC <7 5 4 1>
  171    0 0xffffff7f80b0f000 0x7000     0x7000     net.sf.tuntaposx.tap (1.0) 23FDB715-3D0D-3A26-ACBA-E3794C231CB7 <7 5 4 1>
192-168-2-122:BIN rickhicksted2$ 

192-168-2-122:BIN rickhicksted2$  ifconfig tap0 10.0.0.1
ifconfig: interface tap0 does not exist

192-168-2-122:BIN rickhicksted2$ ls -l /dev/tap*
crw-rw----  1 root  wheel   32,   0 Aug 10 23:19 /dev/tap0
crw-rw----  1 root  wheel   32,   1 Aug 10 23:19 /dev/tap1
crw-rw----  1 root  wheel   32,  10 Aug 10 23:19 /dev/tap10
crw-rw----  1 root  wheel   32,  11 Aug 10 23:19 /dev/tap11
crw-rw----  1 root  wheel   32,  12 Aug 10 23:19 /dev/tap12
crw-rw----  1 root  wheel   32,  13 Aug 10 23:19 /dev/tap13
crw-rw----  1 root  wheel   32,  14 Aug 10 23:19 /dev/tap14
crw-rw----  1 root  wheel   32,  15 Aug 10 23:19 /dev/tap15
crw-rw----  1 root  wheel   32,   2 Aug 10 23:19 /dev/tap2
crw-rw----  1 root  wheel   32,   3 Aug 10 23:19 /dev/tap3
crw-rw----  1 root  wheel   32,   4 Aug 10 23:19 /dev/tap4
crw-rw----  1 root  wheel   32,   5 Aug 10 23:19 /dev/tap5
crw-rw----  1 root  wheel   32,   6 Aug 10 23:19 /dev/tap6
crw-rw----  1 root  wheel   32,   7 Aug 10 23:19 /dev/tap7
crw-rw----  1 root  wheel   32,   8 Aug 10 23:19 /dev/tap8
crw-rw----  1 root  wheel   32,   9 Aug 10 23:19 /dev/tap9

192-168-2-122:BIN rickhicksted2$ cat bridge.sh 
sudo ifconfig bridge1 create
sudo ifconfig bridge1 up addm tap0
sudo ifconfig bridge1 up addm en0
192-168-2-122:BIN rickhicksted2$ ./bridge.sh 
Password:
ifconfig: BRDGADD tap0: No such file or directory

Any ideas?

Thanks,

Rick

**Comment by chenyanlei** [comment]
Hi @tonifirnandes 
I have encountered the same problem, have you solved it?

**Comment by AlmirKadric** [comment]
@rhickstedjr apologies for the late reply. Will answer this anyway for others to have some reference. If the tap interface doesn't appear within ifconfig it means that docker hasn't bound to it. To resolve this restart docker-for-mac manually. Also to help further diagnose the issue the following information should be provided:
 - `ls -l /Applications/Docker.app/Contents/Resources/bin/` to make sure the shim was properly installed and configured
 - `ls -l /dev/tap*` to make sure docker has access to tap interface
 - `ifconfig` to make sure docker connected to the tap interface
 - `netstat -rn` to make sure routes were set to the containers over the tap interface
 - `docker run --rm --privileged --pid=host --net=host alpine ifconfig` to make docker created the target interface
 - `docker run --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i iptables-save` to make sure the docker host allows routing
 - `docker inspect <<Container_id>>` to make sure your container is configure to use all of the above

**Comment by AlmirKadric** [comment]
@chenyanlei can you provide the above information and I'll help you with your issue as well

**Comment by AlmirKadric** [comment]
@chenyanlei @tonifirnandes  are you still facing issues
I would like to clean up this issue
if i dont get a response by next i will be closing the issue

**Comment by AlmirKadric** [comment]
closed due to inactivity

**Comment by tomml** [comment]
Seems not working for new Apple M1 chip? Could anyone confirm?

**Comment by km1562** [comment]
I have the same problem for M1 chip
