### ISSUE TITLE
Install script does not kill Docker gracefully

### ISSUE THREAD

**Issue by hemanthpai** [AlmirKadric-Published/docker-tuntap-osx#28]
When the install script is run, Docker is forced killed by finding its PID. This displays a modal dialog saying docker quit unexpectedly. Also, it doesn't restart. An alternative, is to gracefully quit Docker and restart it ourselves like so:

docker stop $(docker ps -aq) && test -z "$(docker ps -q 2>/dev/null)" && osascript -e 'quit app "Docker"'

open --background -a Docker

I'd like to submit a PR with these changes to the install script if it makes sense.

**Comment by AlmirKadric** [comment]
thanks for this
