### ISSUE TITLE
TunTap sunsetting...suggestions?

### ISSUE THREAD

**Issue by pauldraper** [AlmirKadric-Published/docker-tuntap-osx#32]
It looks like TunTap will no longer be installable starting macOS 10.14.5 

https://sourceforge.net/p/tuntaposx/bugs/28/

Any suggestions for alternatives?

**Comment by AlmirKadric** [comment]
It seems that tunnelblick has resolved the issue withing their build.
I'll reach out to their team to see if we can get that easily available for download as a standalone
If not I will put in the work to do get them into a standalone package
Thanks for bringing this up 👍

**Comment by pauldraper** [comment]
Thank you!

**Comment by genevera** [comment]
Looks like they are providing instructions on how to grab those kexts from the package in that ticket that is linked above.

**Comment by AlmirKadric** [comment]
seems that the system is still working on Catalina (10.15.7)
so I will close this as no longer an issue
let me know if you still have any other issues

**Comment by ghost** [comment]
Working on macOS 11 as well.

**Comment by Mahoney** [comment]
Hope it continues to work. An upgrade to Catalina stopped it working, but uninstalling and reinstalling tuntap via homebrew and / or uninstalling and reinstalling docker_tap brought it back.

[Mattias Nissler's Final Message To His Creation](https://sourceforge.net/p/tuntaposx/mailman/message/37053479/) is a little cryptic on how to replace tuntap:

> As for alternatives, utun will probably cover most cases.
> The Tunnelblick project carries notarized kernel extensions in their github repository, so that's there as an option to try for folks that need tap.
> And finally, perhaps someone (not me) will appear and implement a virtual ethernet device on top of the new-ish userspace driver APIs Apple has introduced.

What is utun and how would I use it? What would I do with Tunnelblick to make it have the same tap effect? And which new-ish userspace driver APIs might I explore? Not that a JVM dev like me is likely to get far with driver APIs.
