### ISSUE TITLE
The output give me the message("The hyperkit executable file was of an unknown type") when execute the install script twice

### ISSUE THREAD

**Issue by wushibin** [AlmirKadric-Published/docker-tuntap-osx#4]
➜  docker-tuntap-osx git:(master) sh ./sbin/docker_tap_install.sh
Password:
**The hyperkit executable file was of an unknown type**

And after i restart the docker application manually, and add the route to my container ip, i still cannot ping my docker containers directly.

**sudo route add -net 172.16.238.20 -netmask 255.255.0.0 10.0.75.1**

Those docker containers are created by the docker-compose with static IPs.
The docker-compose.yml is under: https://github.com/wushibin/kafka-learning/blob/master/docker-compose.yml

Thanks in advance.

**Comment by AlmirKadric** [comment]
Apologies on the late response, last few months have been somewhat crazy for me.

I merged a minor fix which deals with local routing, that may solve your issue.
Do you mind pulling and giving it another try.
If you still have issues please provide me with the following command outputs:
 - `ls -l /Applications/Docker.app/Contents/Resources/bin/` to make sure the shim was properly installed and configured
 - `ls -l /dev/tap*` to make sure docker has access to tap interface
 - `ifconfig` to make sure docker connected to the tap interface
 - `netstat -rn` to make sure routes were set to the containers over the tap interface
 - `docker run --rm --privileged --pid=host --net=host alpine ifconfig` to make docker created the target interface
 - `docker run --rm --privileged --pid=host debian nsenter -t 1 -m -u -n -i iptables-save` to make sure the docker host allows routing
 - `docker inspect <<Container_id>>` to make sure your container is configure to use all of the above

**Comment by AlmirKadric** [comment]
I merged a fix which resolves a lot of the issues inside the setup script.
Please try and pull the latest develop changes and let me know if you still have issues.

**Comment by AlmirKadric** [comment]
will automatically close this issue if no followup by the 10th

**Comment by wushibin** [comment]
sorry for late response.
